language: ruby
sudo: false
cache: bundler

rvm:
- 2.5

branches:
  only:
  - gh-pages

script: bundle exec jekyll build

deploy:
  provider: script
  skip_cleanup: true
  script: gem install s3_website && s3_website push
  on:
    branch: gh-pages

